### ISSUE TITLE
Components won't load well without pre-scraping

### ISSUE THREAD

**Issue by ajz003** [JSR88431/projectThree#10]
We put our scrapes in the componentDidMount for Home.js, but that crashed our app. However, if we try to put the scrape calls in each individual component, the component won't render anything because it takes quite a while to scrape all the data. We have to click on the component link again to show stuff. But then it would scrape again.

For example, in my Forum component, I tried to prevent re-scraping by doing an `axios.get` to see if there is any data already, and if not, THEN it would scrape:

```
    componentDidMount() {
        axios.get("/api/categories/all").then((response) => {
            if (response.data.length === 0) {
                axios.get("/anthony/scrapeDadForum").then(() => {
                    axios.get("/api/categories/all").then((response) => {
                        this.setState({ categoryResults: response.data})
                    })
                })            
            }
            else {
            this.setState({ categoryResults: response.data})
            }

        })
    }

```

However, if the user spams the link, the scrape will happen multiple times before the first scrape has time to finish. Since there still aren't any results from the first `axios.get`, it will scrape multiple times and crash the server.

If anyone has any ideas on how we can prevent re-scraping or pre-scrape everything without bogging down and crashing the server, please help!

**Comment by altaf933** [comment]
Your component should wait for response, normally some progress modal render till your response in props. So actual component will render after see changes in response and modal hide from DOM.
